;;; GENERATED BY ANSIBLE. DO NO EDIT
(ns app.db.config)

(def db {:subprotocol "postgresl"
         :subname "//{{db_host}}/{{db_name}}"
         :user "{{db_user}}"
         :password "{{db_password}}"})
