;;; GENERATED BY ANSIBLE. DO NOT EDIT
;;; EDIT TEMPLATE IN ansible/templates/system_config.clj

;;; The config here will be merged with the config in src/config/main.clj to
;;; product the final main config
(ns config.system)

(def config
  {:ring-port {{ring_port}}
   :nrepl-port {{nrepl_port}}})
